---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bho
  namespace: flux-system
spec:
  interval: 2m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/cat/platforms/bho
  prune: true
  wait: true
  timeout: 2m0s