on:
  workflow_dispatch:

jobs:
  clone-and-copy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout CAT repo
      uses: actions/checkout@v3
      with:
        ref: main  

    - name: Clonare repository SIT
      run: |
        git clone https://github.com/Reny24/TestForCopyFolder.git sit-repo

    - name: Copiare la cartella SIT
      run: |
        cp -r sit-repo/sit ./sit  # Cambia il percorso per adattarlo alla struttura

    - name: Modificare nomi cartelle e contenuti (SIT -> CAT)
      run: |
        # Cambia il nome della cartella SIT in CAT
        mv ./sit ./cat

        # Cerca e sostituisci 'SIT' con 'CAT' nel contenuto dei file
        find ./cat -type f -exec sed -i 's/\bsit\b/cat/g' {} +

    - name: Rimuovere la cartella sit-repo
      run: rm -rf sit-repo

    - name: Commit delle modifiche
      run: |
        git config user.name "Reny24"
        git config user.email "renato_improta@hotmail.it"
        git add .
        git commit -m "Copia cartella sit e modifica da sit a cat"

    # Step 6: Push delle modifiche alla repository CAT
    - name: Push delle modifiche
      run: |
        git push origin main  # Modifica se usi un branch diverso
